#!/bin/bash
cd ~/tools; echo `pwd`
git merge origin/master
cd ~/java-mutil; echo `pwd`
git merge origin/master
cd ~/playground; echo `pwd`
git merge origin/master
cd ~/environment; echo `pwd`
git merge origin/master
cd ~/ocaml-mutil; echo `pwd`
git merge origin/master
cd ~/reverie; echo `pwd`
git merge origin/master
cd ~/mperdikeas.github.com; echo `pwd`
git merge origin/master
cd ~/neuro-jsf-pilot/; echo `pwd`
git merge origin/master
cd ~/neuro-jsf-pilot-envelope/; echo `pwd`
git merge origin/master
