#!/bin/bash
cd environment
echo
git fetch -v
git status -s
git rev-parse HEAD
git ls-remote --heads -q

cd ../ocaml-mutil
echo
git fetch -v
git status -s
git rev-parse HEAD
git ls-remote --heads -q

cd ../playground
echo
git fetch -v
git status -s
git rev-parse HEAD
git ls-remote --heads -q

cd ..
