declare -a repos=("tools" "java-mutil" "environment" "ocaml-mutil" "playground"
                  "mperdikeas.github.com" "archetypes" "clojure-mutil"
                   "zip-diff" "euler-js"
                  "js-react-minesweeper" "js-object-properties" "js-sort-enum" "js-ai-for-shogi-like-games"
                  "js-filtered-datastore" "faker-datastore" "js-react-fixed-data-table-wrapper" "js-react-catch-the-lion"
                  "js-geometry-2d" "js-react-tetris" "js-react-custom-validators"
                  "environment-sensitive" "js-structural-sharing" "js-string-tokenize" "js-react-stack-piling-and-tumbling"
                  "js-fixed-size-lifo" "java-package-refactor" "emacs" "bashrc"
                  "js-algebra" "js-trees" "js-flow-common-types" "js-minmax-wt-alpha-beta-pruning" "js-minmax-naive-but-instructive"
                  "js-checkers-rules-and-eval" "mant-tasks" "google-foobar" "kids-math-exercises"
                 )
