#!/bin/bash
cd ~/tools
git push -v
git status -s
cd ~/java-mutil/
git push -v
git status -s
cd ~/playground
git push -v
git status -s
cd ~/environment
git push -v
git status -s
cd ~/ocaml-mutil
git push -v
git status -s
cd ~/reverie
git push -v
git status -s
cd ~/mperdikeas.github.com/
git push -v
git status -s