#!/bin/bash
cd ~/tools
git ppush
git status -s
cd ~/java-mutil/
git ppush
git status -s
cd ~/playground
git ppush
git status -s
cd ~/environment
git ppush
git status -s
cd ~/ocaml-mutil
git ppush
git status -s
cd ~/reverie
git ppush
git status -s
cd ~/mperdikeas.github.com/
git ppush -v --tags
git status -s
cd ~/archetypes/
git ppush
git status -s