#!/bin/bash
cd ~/tools; echo `pwd`
git merge origin/master
cd ~/java-mutil; echo `pwd`
git merge origin/master
cd ~/playground; echo `pwd`
git merge origin/master
cd ~/environment; echo `pwd`
git merge origin/master
cd ~/ocaml-mutil; echo `pwd`
git merge origin/master
cd ~/mperdikeas.github.com; echo `pwd`
git merge origin/master
cd ~/archetypes/; echo `pwd`
git merge origin/master
cd ~/clojure-mutil/; echo `pwd`
git merge origin/master
cd ~/mant-tasks/; echo `pwd`
git merge origin/master
cd ~/starjava/; echo `pwd`
git merge origin/eurovo-mods
cd ~/zip-diff/; echo `pwd`
git merge origin/master
cd ~/esac-rawdar/; echo `pwd`
git merge origin/master
cd ~/esavo-reg-II/; echo `pwd`
git merge origin/master
cd ~/euler-js/; echo `pwd`
git merge origin/master

